### ISSUE TITLE
Windows Pathnames

### ISSUE THREAD

**Issue by vishaalprasad** [guruucsd/DifferentialEncoding#19]
Running this library on a windows pathname leads to warnings (see end of report). The code then stops after MATLAB can't find the vanhateren images.

Steps to reproduce: run experiments/68x50/sergent_1982/uber_sergent_sergent.m on a Windows machine. You will run into the same problem:

Warning: "C" not found in path. 
> In rmpath (line 57)
  In de_SetupExptPaths (line 18)
  In de_MakeDataset (line 25)
  In de_Simulator (line 18)
  In de_SimulatorUber (line 25)
  In uber_slotnick_de (line 9) 
Warning: "\Users\Vishaal\Documents\GitHub\de\DifferentialEncoding\code\_expts\vanhateren" not found in path. 
> In rmpath (line 57)
  In de_SetupExptPaths (line 18)
  In de_MakeDataset (line 25)
  In de_Simulator (line 18)
  In de_SimulatorUber (line 25)
  In uber_slotnick_de (line 9)

**Comment by bcipolli** [comment]
Thanks @vishaalprasad ; will try this on a virtual machine when I've got time!
