### ISSUE TITLE
Slotnick group plot has inconsistent axes

### ISSUE THREAD

**Issue by bcipolli** [guruucsd/DifferentialEncoding#29]
![image](https://cloud.githubusercontent.com/assets/4072455/11443876/9d1d1174-94d5-11e5-81cb-70449085da10.png)

This plot seems to show a difference in slope for categorical vs coordinate. However, this is not real--it is due to differences in the y axis limits (as the statistical analyses show).

Some common scaling should be used for x- and y-axis, so that eyeballing things will give a sense of real effects / statistical significance.

See https://github.com/guruucsd/DifferentialEncoding/pull/28#issuecomment-158701724

**Comment by bcipolli** [comment]
I hacked this for the VSS code, but we should find a better solution...

**Comment by bcipolli** [comment]
Fixed in https://github.com/bcipolli/DifferentialEncoding/commit/7b9a5c52aed26078b9d3f2bb3a2803d7b132ebf4 ; now `ylim(1) == 0`, and `ylim(2)` is set to something in common.

**Comment by vishaalprasad** [comment]
Fixed by @bcipolli.
