### ISSUE TITLE
Update ADD_EXPERIMENT.md

### ISSUE THREAD

**Issue by bcipolli** [guruucsd/DifferentialEncoding#34]
Seems that this was insufficient to get @vishaalprasad going; needs to be updated.

**Comment by bcipolli** [comment]
@vishaalprasad assigning this to you, since you probably have the best idea of what needs to be documented most.

**Comment by vishaalprasad** [comment]
Fixed with PR #72

**Comment by bcipolli** [comment]
Cool thx. In general, issues should be closed by the person who opens them, after the PR has been merged. Will take a look later today!

**Comment by vishaalprasad** [comment]
@bcipolli Can you close this issue now?

**Comment by bcipolli** [comment]
Ya
