### ISSUE TITLE
Slotnick plots: specify runs per hemisphere.

### ISSUE THREAD

**Issue by bcipolli** [guruucsd/DifferentialEncoding#54]
I've moved the `runs` to the xtick labels. We should pass in the # of good runs per hemisphere (i.e. after rejections) and show them there. It helps understand why errorbars may be different.

**Comment by bcipolli** [comment]
@vishaalprasad can you do this one?

**Comment by vishaalprasad** [comment]
(This should be closed.)

**Comment by bcipolli** [comment]
Nice. Can you close it? You should be an admin...

**Comment by vishaalprasad** [comment]
I can close it next time, but you had told me issues should be closed by the person who opened them!

**Comment by bcipolli** [comment]
Ah, right! True, I didn't realize. Perfect, thanks!

**Comment by vishaalprasad** [comment]
Yeah, that was my fault. Next time, I'll be sure to ping you and also show an image of the issue being fixed (if possible)!
