### ISSUE TITLE
Slotnick paired-squares: equal *and variable* distance from the center line

### ISSUE THREAD

**Issue by bcipolli** [guruucsd/DifferentialEncoding#55]
From Slotnick et al. (2001) (my emphasis): 
>For the paired squares task, two small squares were presented on the left side of the page an *equal and variable distance* from the center of the left side of the page in the horizontal dimension and two small squares were also presented on the right side of the page an *equal and variable distance from the center* of the right side of the page

What I see in the code is that the center position between the dots is fixed at the "quarter line":
https://github.com/bcipolli/DifferentialEncoding/blob/70217afbd8019acbb5ba5fd06b0b957642de380a/code/_expts/slotnick_etal_2001/de_StimCreate.m#L173

We should make that distance variable.
@vishaalprasad , assigning this to you.

**Comment by vishaalprasad** [comment]
> an equal and variable distance from the center of the right side of the page

is equivalent to each quarter line that exists in the line, so this has already been completed.

Closing this issue.
